### ISSUE TITLE
<type 'exceptions.ImportError'> No module named Base

### ISSUE THREAD

**Issue by snowman** [richardpenman/wswp_places#7]
### Exception
<type 'exceptions.ImportError'> No module named Base

### Version
web2py™	Version 2.21.1-stable+timestamp.2020.11.28.04.10.44
Python	Python 2.7.18: /usr/sbin/python2 (prefix: /usr)

### Traceback
```code
Traceback (most recent call last):
  File "/tmp/web/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/tmp/web/web2py/applications/places/controllers/default.py", line 100, in <module>
  File "/tmp/web/web2py/gluon/globals.py", line 430, in <lambda>
    self._caller = lambda f: f()
  File "/tmp/web/web2py/applications/places/controllers/default.py", line 87, in user
    captcha = local_import('captcha', reload=REFRESH)
  File "/tmp/web/web2py/gluon/compileapp.py", line 397, in <lambda>
    local_import_aux(name, reload, app)
  File "/tmp/web/web2py/gluon/compileapp.py", line 282, in local_import_aux
    module = __import__(name)
  File "/tmp/web/web2py/gluon/custom_import.py", line 87, in custom_importer
    return NATIVE_IMPORTER(name, globals, locals, fromlist, level)
  File "applications/places/modules/captcha.py", line 8, in <module>
    from Captcha.Visual import Text, Backgrounds, ImageCaptcha
  File "/tmp/web/web2py/gluon/custom_import.py", line 85, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "applications/places/modules/Captcha/Visual/__init__.py", line 12, in <module>
    from Base import *
  File "/tmp/web/web2py/gluon/custom_import.py", line 85, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
ImportError: No module named Base
```
## Error snapshot

<type 'exceptions.ImportError'>(No module named Base)

## Frames
```
File /tmp/web/web2py/gluon/restricted.py in restricted at line 219 code arguments variables

File /tmp/web/web2py/applications/places/controllers/default.py in <module> at line 100 code arguments variables

File /tmp/web/web2py/gluon/globals.py in <lambda> at line 430 code arguments variables

File /tmp/web/web2py/applications/places/controllers/default.py in user at line 87 code arguments variables

File /tmp/web/web2py/gluon/compileapp.py in <lambda> at line 397 code arguments variables

File /tmp/web/web2py/gluon/compileapp.py in local_import_aux at line 282 code arguments variables

File /tmp/web/web2py/gluon/custom_import.py in custom_importer at line 87 code arguments variables

File /tmp/web/web2py/applications/places/modules/captcha.py in <module> at line 8 code arguments variables

File /tmp/web/web2py/gluon/custom_import.py in custom_importer at line 85 code arguments variables

File /tmp/web/web2py/applications/places/modules/Captcha/Visual/__init__.py in <module> at line 12 code arguments variables

File /tmp/web/web2py/gluon/custom_import.py in custom_importer at line 85 code arguments variables
```
## Function argument list

(name='Base', globals={'__builtins__': {'ArithmeticError': <type 'exceptions.ArithmeticError'>, 'AssertionError': <type 'exceptions.AssertionError'>, 'AttributeError': <type 'exceptions.AttributeError'>, 'BaseException': <type 'exceptions.BaseException'>, 'BufferError': <type 'exceptions.BufferError'>, 'BytesWarning': <type 'exceptions.BytesWarning'>, 'DeprecationWarning': <type 'exceptions.DeprecationWarning'>, 'EOFError': <type 'exceptions.EOFError'>, 'Ellipsis': Ellipsis, 'EnvironmentError': <type 'exceptions.EnvironmentError'>, ...}, '__doc__': None, '__file__': None, '__name__': None, '__package__': None, '__path__': None}, locals={'__builtins__': {'ArithmeticError': <type 'exceptions.ArithmeticError'>, 'AssertionError': <type 'exceptions.AssertionError'>, 'AttributeError': <type 'exceptions.AttributeError'>, 'BaseException': <type 'exceptions.BaseException'>, 'BufferError': <type 'exceptions.BufferError'>, 'BytesWarning': <type 'exceptions.BytesWarning'>, 'DeprecationWarning': <type 'exceptions.DeprecationWarning'>, 'EOFError': <type 'exceptions.EOFError'>, 'Ellipsis': Ellipsis, 'EnvironmentError': <type 'exceptions.EnvironmentError'>, ...}, '__doc__': None, '__file__': None, '__name__': None, '__package__': None, '__path__': None}, fromlist=('*',), level=-1)

## Code listing
```
                        raise ImportError("No module named %s" % modules_prefix)
            return result
        else:
            # "from x import a, b, ..."
            pname = "%s.%s" % (modules_prefix, name)
            return base_importer(pname, globals, locals, fromlist, level)

    return NATIVE_IMPORTER(name, globals, locals, fromlist, level)
```
## In file: /tmp/web/web2py/applications/places/controllers/default.py
<code object <module> at 0x7f6e8976dcb0, file "/tmp/web/web2py/applications/places/controllers/default.py", line 4>

**Comment by snowman** [comment]
1. use `Python 2.X` version

2. `$ python2 -m pip install Pillow`

3. in dir `modules/Captcha/Visual/`:
   ```code
   modify file "Backgrounds.py" : from PIL import ImageDraw, Image
   modify file "Base.py"        : from PIL import Image
   modify file "Distortions.py" : from PIL import ImageDraw, Image
   modify file "__init__.py"    : from Captcha.Visual.Base import *
   modify file "Pictures.py"    : from PIL import Image
   modify file "Text.py"        : from PIL import ImageFont, ImageDraw
   ```

4. in file `models/1_db.py`:
    ```code
      from gluon.tools import Auth, Crud, Service, PluginManager, Recaptcha2 as Recaptcha, prettydate
    ```
